version: '3.8'

services:
  # Base de datos H2 (opcional, para desarrollo)
  h2-database:
    image: oscarfonts/h2
    container_name: agenda-h2-db
    ports:
      - "9092:81"
    environment:
      H2_OPTIONS: "-ifNotExists"
    volumes:
      - h2-data:/h2-data
    networks:
      - agenda-network
    profiles:
      - development

  # Backend Spring Boot
  backend:
    build:
      context: ./backend-ci-cd
      dockerfile: Dockerfile
    container_name: agenda-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./data/agenda
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_H2_CONSOLE_ENABLED=true
    volumes:
      - backend-data:/app/data
    networks:
      - agenda-network
    depends_on:
      - h2-database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/contactos"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React
  frontend:
    build:
      context: ./frontend-ci-cd
      dockerfile: Dockerfile
    container_name: agenda-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    networks:
      - agenda-network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (opcional, para producción)
  nginx:
    image: nginx:alpine
    container_name: agenda-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - agenda-network
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    profiles:
      - production

volumes:
  h2-data:
    driver: local
  backend-data:
    driver: local

networks:
  agenda-network:
    driver: bridge
